---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ibmsspac/api.oakaudix.app/
    - /bin/cp -R backend $DEPLOYPATH
    - cd $DEPLOYPATH/backend
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - chmod -R 775 storage bootstrap/cache

