/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowAdminRouteImport } from './routes/workflow-admin'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ProcessAuditsRouteImport } from './routes/process-audits'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowAdminRoute = WorkflowAdminRouteImport.update({
  id: '/workflow-admin',
  path: '/workflow-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessAuditsRoute = ProcessAuditsRouteImport.update({
  id: '/process-audits',
  path: '/process-audits',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/dashboard': typeof DashboardRoute
  '/process-audits': typeof ProcessAuditsRoute
  '/workflow': typeof WorkflowRoute
  '/workflow-admin': typeof WorkflowAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/dashboard': typeof DashboardRoute
  '/process-audits': typeof ProcessAuditsRoute
  '/workflow': typeof WorkflowRoute
  '/workflow-admin': typeof WorkflowAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/dashboard': typeof DashboardRoute
  '/process-audits': typeof ProcessAuditsRoute
  '/workflow': typeof WorkflowRoute
  '/workflow-admin': typeof WorkflowAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklists'
    | '/dashboard'
    | '/process-audits'
    | '/workflow'
    | '/workflow-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklists'
    | '/dashboard'
    | '/process-audits'
    | '/workflow'
    | '/workflow-admin'
  id:
    | '__root__'
    | '/'
    | '/checklists'
    | '/dashboard'
    | '/process-audits'
    | '/workflow'
    | '/workflow-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistsRoute: typeof ChecklistsRoute
  DashboardRoute: typeof DashboardRoute
  ProcessAuditsRoute: typeof ProcessAuditsRoute
  WorkflowRoute: typeof WorkflowRoute
  WorkflowAdminRoute: typeof WorkflowAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow-admin': {
      id: '/workflow-admin'
      path: '/workflow-admin'
      fullPath: '/workflow-admin'
      preLoaderRoute: typeof WorkflowAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-audits': {
      id: '/process-audits'
      path: '/process-audits'
      fullPath: '/process-audits'
      preLoaderRoute: typeof ProcessAuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistsRoute: ChecklistsRoute,
  DashboardRoute: DashboardRoute,
  ProcessAuditsRoute: ProcessAuditsRoute,
  WorkflowRoute: WorkflowRoute,
  WorkflowAdminRoute: WorkflowAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
