/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersTeamsRouteImport } from './routes/users.teams'
import { Route as UsersRolesRouteImport } from './routes/users.roles'
import { Route as UsersPermissionsRouteImport } from './routes/users.permissions'
import { Route as UsersAllRouteImport } from './routes/users.all'
import { Route as RiskTreatmentRouteImport } from './routes/risk.treatment'
import { Route as RiskRegisterRouteImport } from './routes/risk.register'
import { Route as RiskOpportunitiesRouteImport } from './routes/risk.opportunities'
import { Route as RiskAssessmentRouteImport } from './routes/risk.assessment'
import { Route as OrgProcessesRouteImport } from './routes/org.processes'
import { Route as OrgLocationsRouteImport } from './routes/org.locations'
import { Route as OrgDepartmentsRouteImport } from './routes/org.departments'
import { Route as OrgAssetsRouteImport } from './routes/org.assets'
import { Route as NcOfiRouteImport } from './routes/nc.ofi'
import { Route as NcObservationsRouteImport } from './routes/nc.observations'
import { Route as NcMinorRouteImport } from './routes/nc.minor'
import { Route as NcMajorRouteImport } from './routes/nc.major'
import { Route as LibraryTemplatesRouteImport } from './routes/library.templates'
import { Route as LibraryStandardsRouteImport } from './routes/library.standards'
import { Route as LibraryProceduresRouteImport } from './routes/library.procedures'
import { Route as LibraryPoliciesRouteImport } from './routes/library.policies'
import { Route as LibraryFormsRouteImport } from './routes/library.forms'
import { Route as ExecutionNotesRouteImport } from './routes/execution.notes'
import { Route as ExecutionFindingsRouteImport } from './routes/execution.findings'
import { Route as ExecutionEvidenceRouteImport } from './routes/execution.evidence'
import { Route as ExecutionConductRouteImport } from './routes/execution.conduct'
import { Route as ExecutionChecklistsRouteImport } from './routes/execution.checklists'
import { Route as AuditsScheduleRouteImport } from './routes/audits.schedule'
import { Route as AuditsProgramRouteImport } from './routes/audits.program'
import { Route as AuditsPlansRouteImport } from './routes/audits.plans'
import { Route as AuditsNewRouteImport } from './routes/audits.new'
import { Route as AuditsCalendarRouteImport } from './routes/audits.calendar'
import { Route as ActionsOverdueRouteImport } from './routes/actions.overdue'
import { Route as ActionsOpenRouteImport } from './routes/actions.open'
import { Route as ActionsInProgressRouteImport } from './routes/actions.in-progress'
import { Route as ActionsClosedRouteImport } from './routes/actions.closed'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersTeamsRoute = UsersTeamsRouteImport.update({
  id: '/users/teams',
  path: '/users/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRolesRoute = UsersRolesRouteImport.update({
  id: '/users/roles',
  path: '/users/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersPermissionsRoute = UsersPermissionsRouteImport.update({
  id: '/users/permissions',
  path: '/users/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersAllRoute = UsersAllRouteImport.update({
  id: '/users/all',
  path: '/users/all',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskTreatmentRoute = RiskTreatmentRouteImport.update({
  id: '/risk/treatment',
  path: '/risk/treatment',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRegisterRoute = RiskRegisterRouteImport.update({
  id: '/risk/register',
  path: '/risk/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskOpportunitiesRoute = RiskOpportunitiesRouteImport.update({
  id: '/risk/opportunities',
  path: '/risk/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAssessmentRoute = RiskAssessmentRouteImport.update({
  id: '/risk/assessment',
  path: '/risk/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgProcessesRoute = OrgProcessesRouteImport.update({
  id: '/org/processes',
  path: '/org/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgLocationsRoute = OrgLocationsRouteImport.update({
  id: '/org/locations',
  path: '/org/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgDepartmentsRoute = OrgDepartmentsRouteImport.update({
  id: '/org/departments',
  path: '/org/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgAssetsRoute = OrgAssetsRouteImport.update({
  id: '/org/assets',
  path: '/org/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const NcOfiRoute = NcOfiRouteImport.update({
  id: '/nc/ofi',
  path: '/nc/ofi',
  getParentRoute: () => rootRouteImport,
} as any)
const NcObservationsRoute = NcObservationsRouteImport.update({
  id: '/nc/observations',
  path: '/nc/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const NcMinorRoute = NcMinorRouteImport.update({
  id: '/nc/minor',
  path: '/nc/minor',
  getParentRoute: () => rootRouteImport,
} as any)
const NcMajorRoute = NcMajorRouteImport.update({
  id: '/nc/major',
  path: '/nc/major',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryTemplatesRoute = LibraryTemplatesRouteImport.update({
  id: '/library/templates',
  path: '/library/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryStandardsRoute = LibraryStandardsRouteImport.update({
  id: '/library/standards',
  path: '/library/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryProceduresRoute = LibraryProceduresRouteImport.update({
  id: '/library/procedures',
  path: '/library/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPoliciesRoute = LibraryPoliciesRouteImport.update({
  id: '/library/policies',
  path: '/library/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryFormsRoute = LibraryFormsRouteImport.update({
  id: '/library/forms',
  path: '/library/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionNotesRoute = ExecutionNotesRouteImport.update({
  id: '/execution/notes',
  path: '/execution/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionFindingsRoute = ExecutionFindingsRouteImport.update({
  id: '/execution/findings',
  path: '/execution/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionEvidenceRoute = ExecutionEvidenceRouteImport.update({
  id: '/execution/evidence',
  path: '/execution/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionConductRoute = ExecutionConductRouteImport.update({
  id: '/execution/conduct',
  path: '/execution/conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionChecklistsRoute = ExecutionChecklistsRouteImport.update({
  id: '/execution/checklists',
  path: '/execution/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsScheduleRoute = AuditsScheduleRouteImport.update({
  id: '/audits/schedule',
  path: '/audits/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsProgramRoute = AuditsProgramRouteImport.update({
  id: '/audits/program',
  path: '/audits/program',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsPlansRoute = AuditsPlansRouteImport.update({
  id: '/audits/plans',
  path: '/audits/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsNewRoute = AuditsNewRouteImport.update({
  id: '/audits/new',
  path: '/audits/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsCalendarRoute = AuditsCalendarRouteImport.update({
  id: '/audits/calendar',
  path: '/audits/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsOverdueRoute = ActionsOverdueRouteImport.update({
  id: '/actions/overdue',
  path: '/actions/overdue',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsOpenRoute = ActionsOpenRouteImport.update({
  id: '/actions/open',
  path: '/actions/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsInProgressRoute = ActionsInProgressRouteImport.update({
  id: '/actions/in-progress',
  path: '/actions/in-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsClosedRoute = ActionsClosedRouteImport.update({
  id: '/actions/closed',
  path: '/actions/closed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/actions/closed': typeof ActionsClosedRoute
  '/actions/in-progress': typeof ActionsInProgressRoute
  '/actions/open': typeof ActionsOpenRoute
  '/actions/overdue': typeof ActionsOverdueRoute
  '/audits/calendar': typeof AuditsCalendarRoute
  '/audits/new': typeof AuditsNewRoute
  '/audits/plans': typeof AuditsPlansRoute
  '/audits/program': typeof AuditsProgramRoute
  '/audits/schedule': typeof AuditsScheduleRoute
  '/execution/checklists': typeof ExecutionChecklistsRoute
  '/execution/conduct': typeof ExecutionConductRoute
  '/execution/evidence': typeof ExecutionEvidenceRoute
  '/execution/findings': typeof ExecutionFindingsRoute
  '/execution/notes': typeof ExecutionNotesRoute
  '/library/forms': typeof LibraryFormsRoute
  '/library/policies': typeof LibraryPoliciesRoute
  '/library/procedures': typeof LibraryProceduresRoute
  '/library/standards': typeof LibraryStandardsRoute
  '/library/templates': typeof LibraryTemplatesRoute
  '/nc/major': typeof NcMajorRoute
  '/nc/minor': typeof NcMinorRoute
  '/nc/observations': typeof NcObservationsRoute
  '/nc/ofi': typeof NcOfiRoute
  '/org/assets': typeof OrgAssetsRoute
  '/org/departments': typeof OrgDepartmentsRoute
  '/org/locations': typeof OrgLocationsRoute
  '/org/processes': typeof OrgProcessesRoute
  '/risk/assessment': typeof RiskAssessmentRoute
  '/risk/opportunities': typeof RiskOpportunitiesRoute
  '/risk/register': typeof RiskRegisterRoute
  '/risk/treatment': typeof RiskTreatmentRoute
  '/users/all': typeof UsersAllRoute
  '/users/permissions': typeof UsersPermissionsRoute
  '/users/roles': typeof UsersRolesRoute
  '/users/teams': typeof UsersTeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/actions/closed': typeof ActionsClosedRoute
  '/actions/in-progress': typeof ActionsInProgressRoute
  '/actions/open': typeof ActionsOpenRoute
  '/actions/overdue': typeof ActionsOverdueRoute
  '/audits/calendar': typeof AuditsCalendarRoute
  '/audits/new': typeof AuditsNewRoute
  '/audits/plans': typeof AuditsPlansRoute
  '/audits/program': typeof AuditsProgramRoute
  '/audits/schedule': typeof AuditsScheduleRoute
  '/execution/checklists': typeof ExecutionChecklistsRoute
  '/execution/conduct': typeof ExecutionConductRoute
  '/execution/evidence': typeof ExecutionEvidenceRoute
  '/execution/findings': typeof ExecutionFindingsRoute
  '/execution/notes': typeof ExecutionNotesRoute
  '/library/forms': typeof LibraryFormsRoute
  '/library/policies': typeof LibraryPoliciesRoute
  '/library/procedures': typeof LibraryProceduresRoute
  '/library/standards': typeof LibraryStandardsRoute
  '/library/templates': typeof LibraryTemplatesRoute
  '/nc/major': typeof NcMajorRoute
  '/nc/minor': typeof NcMinorRoute
  '/nc/observations': typeof NcObservationsRoute
  '/nc/ofi': typeof NcOfiRoute
  '/org/assets': typeof OrgAssetsRoute
  '/org/departments': typeof OrgDepartmentsRoute
  '/org/locations': typeof OrgLocationsRoute
  '/org/processes': typeof OrgProcessesRoute
  '/risk/assessment': typeof RiskAssessmentRoute
  '/risk/opportunities': typeof RiskOpportunitiesRoute
  '/risk/register': typeof RiskRegisterRoute
  '/risk/treatment': typeof RiskTreatmentRoute
  '/users/all': typeof UsersAllRoute
  '/users/permissions': typeof UsersPermissionsRoute
  '/users/roles': typeof UsersRolesRoute
  '/users/teams': typeof UsersTeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/actions/closed': typeof ActionsClosedRoute
  '/actions/in-progress': typeof ActionsInProgressRoute
  '/actions/open': typeof ActionsOpenRoute
  '/actions/overdue': typeof ActionsOverdueRoute
  '/audits/calendar': typeof AuditsCalendarRoute
  '/audits/new': typeof AuditsNewRoute
  '/audits/plans': typeof AuditsPlansRoute
  '/audits/program': typeof AuditsProgramRoute
  '/audits/schedule': typeof AuditsScheduleRoute
  '/execution/checklists': typeof ExecutionChecklistsRoute
  '/execution/conduct': typeof ExecutionConductRoute
  '/execution/evidence': typeof ExecutionEvidenceRoute
  '/execution/findings': typeof ExecutionFindingsRoute
  '/execution/notes': typeof ExecutionNotesRoute
  '/library/forms': typeof LibraryFormsRoute
  '/library/policies': typeof LibraryPoliciesRoute
  '/library/procedures': typeof LibraryProceduresRoute
  '/library/standards': typeof LibraryStandardsRoute
  '/library/templates': typeof LibraryTemplatesRoute
  '/nc/major': typeof NcMajorRoute
  '/nc/minor': typeof NcMinorRoute
  '/nc/observations': typeof NcObservationsRoute
  '/nc/ofi': typeof NcOfiRoute
  '/org/assets': typeof OrgAssetsRoute
  '/org/departments': typeof OrgDepartmentsRoute
  '/org/locations': typeof OrgLocationsRoute
  '/org/processes': typeof OrgProcessesRoute
  '/risk/assessment': typeof RiskAssessmentRoute
  '/risk/opportunities': typeof RiskOpportunitiesRoute
  '/risk/register': typeof RiskRegisterRoute
  '/risk/treatment': typeof RiskTreatmentRoute
  '/users/all': typeof UsersAllRoute
  '/users/permissions': typeof UsersPermissionsRoute
  '/users/roles': typeof UsersRolesRoute
  '/users/teams': typeof UsersTeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/privacy'
    | '/reports'
    | '/settings'
    | '/terms'
    | '/actions/closed'
    | '/actions/in-progress'
    | '/actions/open'
    | '/actions/overdue'
    | '/audits/calendar'
    | '/audits/new'
    | '/audits/plans'
    | '/audits/program'
    | '/audits/schedule'
    | '/execution/checklists'
    | '/execution/conduct'
    | '/execution/evidence'
    | '/execution/findings'
    | '/execution/notes'
    | '/library/forms'
    | '/library/policies'
    | '/library/procedures'
    | '/library/standards'
    | '/library/templates'
    | '/nc/major'
    | '/nc/minor'
    | '/nc/observations'
    | '/nc/ofi'
    | '/org/assets'
    | '/org/departments'
    | '/org/locations'
    | '/org/processes'
    | '/risk/assessment'
    | '/risk/opportunities'
    | '/risk/register'
    | '/risk/treatment'
    | '/users/all'
    | '/users/permissions'
    | '/users/roles'
    | '/users/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/privacy'
    | '/reports'
    | '/settings'
    | '/terms'
    | '/actions/closed'
    | '/actions/in-progress'
    | '/actions/open'
    | '/actions/overdue'
    | '/audits/calendar'
    | '/audits/new'
    | '/audits/plans'
    | '/audits/program'
    | '/audits/schedule'
    | '/execution/checklists'
    | '/execution/conduct'
    | '/execution/evidence'
    | '/execution/findings'
    | '/execution/notes'
    | '/library/forms'
    | '/library/policies'
    | '/library/procedures'
    | '/library/standards'
    | '/library/templates'
    | '/nc/major'
    | '/nc/minor'
    | '/nc/observations'
    | '/nc/ofi'
    | '/org/assets'
    | '/org/departments'
    | '/org/locations'
    | '/org/processes'
    | '/risk/assessment'
    | '/risk/opportunities'
    | '/risk/register'
    | '/risk/treatment'
    | '/users/all'
    | '/users/permissions'
    | '/users/roles'
    | '/users/teams'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/privacy'
    | '/reports'
    | '/settings'
    | '/terms'
    | '/actions/closed'
    | '/actions/in-progress'
    | '/actions/open'
    | '/actions/overdue'
    | '/audits/calendar'
    | '/audits/new'
    | '/audits/plans'
    | '/audits/program'
    | '/audits/schedule'
    | '/execution/checklists'
    | '/execution/conduct'
    | '/execution/evidence'
    | '/execution/findings'
    | '/execution/notes'
    | '/library/forms'
    | '/library/policies'
    | '/library/procedures'
    | '/library/standards'
    | '/library/templates'
    | '/nc/major'
    | '/nc/minor'
    | '/nc/observations'
    | '/nc/ofi'
    | '/org/assets'
    | '/org/departments'
    | '/org/locations'
    | '/org/processes'
    | '/risk/assessment'
    | '/risk/opportunities'
    | '/risk/register'
    | '/risk/treatment'
    | '/users/all'
    | '/users/permissions'
    | '/users/roles'
    | '/users/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ActionsClosedRoute: typeof ActionsClosedRoute
  ActionsInProgressRoute: typeof ActionsInProgressRoute
  ActionsOpenRoute: typeof ActionsOpenRoute
  ActionsOverdueRoute: typeof ActionsOverdueRoute
  AuditsCalendarRoute: typeof AuditsCalendarRoute
  AuditsNewRoute: typeof AuditsNewRoute
  AuditsPlansRoute: typeof AuditsPlansRoute
  AuditsProgramRoute: typeof AuditsProgramRoute
  AuditsScheduleRoute: typeof AuditsScheduleRoute
  ExecutionChecklistsRoute: typeof ExecutionChecklistsRoute
  ExecutionConductRoute: typeof ExecutionConductRoute
  ExecutionEvidenceRoute: typeof ExecutionEvidenceRoute
  ExecutionFindingsRoute: typeof ExecutionFindingsRoute
  ExecutionNotesRoute: typeof ExecutionNotesRoute
  LibraryFormsRoute: typeof LibraryFormsRoute
  LibraryPoliciesRoute: typeof LibraryPoliciesRoute
  LibraryProceduresRoute: typeof LibraryProceduresRoute
  LibraryStandardsRoute: typeof LibraryStandardsRoute
  LibraryTemplatesRoute: typeof LibraryTemplatesRoute
  NcMajorRoute: typeof NcMajorRoute
  NcMinorRoute: typeof NcMinorRoute
  NcObservationsRoute: typeof NcObservationsRoute
  NcOfiRoute: typeof NcOfiRoute
  OrgAssetsRoute: typeof OrgAssetsRoute
  OrgDepartmentsRoute: typeof OrgDepartmentsRoute
  OrgLocationsRoute: typeof OrgLocationsRoute
  OrgProcessesRoute: typeof OrgProcessesRoute
  RiskAssessmentRoute: typeof RiskAssessmentRoute
  RiskOpportunitiesRoute: typeof RiskOpportunitiesRoute
  RiskRegisterRoute: typeof RiskRegisterRoute
  RiskTreatmentRoute: typeof RiskTreatmentRoute
  UsersAllRoute: typeof UsersAllRoute
  UsersPermissionsRoute: typeof UsersPermissionsRoute
  UsersRolesRoute: typeof UsersRolesRoute
  UsersTeamsRoute: typeof UsersTeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/teams': {
      id: '/users/teams'
      path: '/users/teams'
      fullPath: '/users/teams'
      preLoaderRoute: typeof UsersTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/roles': {
      id: '/users/roles'
      path: '/users/roles'
      fullPath: '/users/roles'
      preLoaderRoute: typeof UsersRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/permissions': {
      id: '/users/permissions'
      path: '/users/permissions'
      fullPath: '/users/permissions'
      preLoaderRoute: typeof UsersPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/all': {
      id: '/users/all'
      path: '/users/all'
      fullPath: '/users/all'
      preLoaderRoute: typeof UsersAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/treatment': {
      id: '/risk/treatment'
      path: '/risk/treatment'
      fullPath: '/risk/treatment'
      preLoaderRoute: typeof RiskTreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/register': {
      id: '/risk/register'
      path: '/risk/register'
      fullPath: '/risk/register'
      preLoaderRoute: typeof RiskRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/opportunities': {
      id: '/risk/opportunities'
      path: '/risk/opportunities'
      fullPath: '/risk/opportunities'
      preLoaderRoute: typeof RiskOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/assessment': {
      id: '/risk/assessment'
      path: '/risk/assessment'
      fullPath: '/risk/assessment'
      preLoaderRoute: typeof RiskAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/processes': {
      id: '/org/processes'
      path: '/org/processes'
      fullPath: '/org/processes'
      preLoaderRoute: typeof OrgProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/locations': {
      id: '/org/locations'
      path: '/org/locations'
      fullPath: '/org/locations'
      preLoaderRoute: typeof OrgLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/departments': {
      id: '/org/departments'
      path: '/org/departments'
      fullPath: '/org/departments'
      preLoaderRoute: typeof OrgDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/assets': {
      id: '/org/assets'
      path: '/org/assets'
      fullPath: '/org/assets'
      preLoaderRoute: typeof OrgAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nc/ofi': {
      id: '/nc/ofi'
      path: '/nc/ofi'
      fullPath: '/nc/ofi'
      preLoaderRoute: typeof NcOfiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nc/observations': {
      id: '/nc/observations'
      path: '/nc/observations'
      fullPath: '/nc/observations'
      preLoaderRoute: typeof NcObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nc/minor': {
      id: '/nc/minor'
      path: '/nc/minor'
      fullPath: '/nc/minor'
      preLoaderRoute: typeof NcMinorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nc/major': {
      id: '/nc/major'
      path: '/nc/major'
      fullPath: '/nc/major'
      preLoaderRoute: typeof NcMajorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/templates': {
      id: '/library/templates'
      path: '/library/templates'
      fullPath: '/library/templates'
      preLoaderRoute: typeof LibraryTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/standards': {
      id: '/library/standards'
      path: '/library/standards'
      fullPath: '/library/standards'
      preLoaderRoute: typeof LibraryStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/procedures': {
      id: '/library/procedures'
      path: '/library/procedures'
      fullPath: '/library/procedures'
      preLoaderRoute: typeof LibraryProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/policies': {
      id: '/library/policies'
      path: '/library/policies'
      fullPath: '/library/policies'
      preLoaderRoute: typeof LibraryPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/forms': {
      id: '/library/forms'
      path: '/library/forms'
      fullPath: '/library/forms'
      preLoaderRoute: typeof LibraryFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution/notes': {
      id: '/execution/notes'
      path: '/execution/notes'
      fullPath: '/execution/notes'
      preLoaderRoute: typeof ExecutionNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution/findings': {
      id: '/execution/findings'
      path: '/execution/findings'
      fullPath: '/execution/findings'
      preLoaderRoute: typeof ExecutionFindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution/evidence': {
      id: '/execution/evidence'
      path: '/execution/evidence'
      fullPath: '/execution/evidence'
      preLoaderRoute: typeof ExecutionEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution/conduct': {
      id: '/execution/conduct'
      path: '/execution/conduct'
      fullPath: '/execution/conduct'
      preLoaderRoute: typeof ExecutionConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution/checklists': {
      id: '/execution/checklists'
      path: '/execution/checklists'
      fullPath: '/execution/checklists'
      preLoaderRoute: typeof ExecutionChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/schedule': {
      id: '/audits/schedule'
      path: '/audits/schedule'
      fullPath: '/audits/schedule'
      preLoaderRoute: typeof AuditsScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/program': {
      id: '/audits/program'
      path: '/audits/program'
      fullPath: '/audits/program'
      preLoaderRoute: typeof AuditsProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/plans': {
      id: '/audits/plans'
      path: '/audits/plans'
      fullPath: '/audits/plans'
      preLoaderRoute: typeof AuditsPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/new': {
      id: '/audits/new'
      path: '/audits/new'
      fullPath: '/audits/new'
      preLoaderRoute: typeof AuditsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/calendar': {
      id: '/audits/calendar'
      path: '/audits/calendar'
      fullPath: '/audits/calendar'
      preLoaderRoute: typeof AuditsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/overdue': {
      id: '/actions/overdue'
      path: '/actions/overdue'
      fullPath: '/actions/overdue'
      preLoaderRoute: typeof ActionsOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/open': {
      id: '/actions/open'
      path: '/actions/open'
      fullPath: '/actions/open'
      preLoaderRoute: typeof ActionsOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/in-progress': {
      id: '/actions/in-progress'
      path: '/actions/in-progress'
      fullPath: '/actions/in-progress'
      preLoaderRoute: typeof ActionsInProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/closed': {
      id: '/actions/closed'
      path: '/actions/closed'
      fullPath: '/actions/closed'
      preLoaderRoute: typeof ActionsClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ActionsClosedRoute: ActionsClosedRoute,
  ActionsInProgressRoute: ActionsInProgressRoute,
  ActionsOpenRoute: ActionsOpenRoute,
  ActionsOverdueRoute: ActionsOverdueRoute,
  AuditsCalendarRoute: AuditsCalendarRoute,
  AuditsNewRoute: AuditsNewRoute,
  AuditsPlansRoute: AuditsPlansRoute,
  AuditsProgramRoute: AuditsProgramRoute,
  AuditsScheduleRoute: AuditsScheduleRoute,
  ExecutionChecklistsRoute: ExecutionChecklistsRoute,
  ExecutionConductRoute: ExecutionConductRoute,
  ExecutionEvidenceRoute: ExecutionEvidenceRoute,
  ExecutionFindingsRoute: ExecutionFindingsRoute,
  ExecutionNotesRoute: ExecutionNotesRoute,
  LibraryFormsRoute: LibraryFormsRoute,
  LibraryPoliciesRoute: LibraryPoliciesRoute,
  LibraryProceduresRoute: LibraryProceduresRoute,
  LibraryStandardsRoute: LibraryStandardsRoute,
  LibraryTemplatesRoute: LibraryTemplatesRoute,
  NcMajorRoute: NcMajorRoute,
  NcMinorRoute: NcMinorRoute,
  NcObservationsRoute: NcObservationsRoute,
  NcOfiRoute: NcOfiRoute,
  OrgAssetsRoute: OrgAssetsRoute,
  OrgDepartmentsRoute: OrgDepartmentsRoute,
  OrgLocationsRoute: OrgLocationsRoute,
  OrgProcessesRoute: OrgProcessesRoute,
  RiskAssessmentRoute: RiskAssessmentRoute,
  RiskOpportunitiesRoute: RiskOpportunitiesRoute,
  RiskRegisterRoute: RiskRegisterRoute,
  RiskTreatmentRoute: RiskTreatmentRoute,
  UsersAllRoute: UsersAllRoute,
  UsersPermissionsRoute: UsersPermissionsRoute,
  UsersRolesRoute: UsersRolesRoute,
  UsersTeamsRoute: UsersTeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
